models:
  gemma3:
    model: ai/gemma3-qat

services:
  project-setup:
    image: michaelirwin244/workshop-poc:setup
    pull_policy: always
    volumes:
      - project:/project
    environment:
      PROJECT_CLONE_URL: https://github.com/dockersamples/workshop-agentic-compose.git


  workspace:
    image: michaelirwin244/workshop-environment
    pull_policy: always
    command: /home/coder/project
    ports:
      - 8085:8085
    depends_on:
      project-setup:
        condition: service_completed_successfully
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock    
      # - project:/home/coder/project
      - ./:/home/coder/project
    environment:
      MODEL_RUNNER_HOST: http://model-runner.docker.internal
      OPENAI_BASE_URL: http://model-runner.docker.internal/engines/v1
      OPENAI_API_KEY: not-required
      OPENAI_MODEL: ai/gemma3-qat

  visual-chatbot:
    image: mikesir87/visual-chatbot
    use_api_socket: true
    ports:
      - 3000:3000
    models:
      gemma3:
        endpoint_var: OPENAI_BASE_URL
        model_var: OPENAI_MODEL

volumes:
  project: